accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'  # Set the app_name here

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('dashboard', views.dashboard, name = 'dashboard'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('shop.urls', namespace='shop')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('shop1/', include('shop1.urls', namespace='shop1')),
    path('shop2/', include('shop2.urls', namespace='shop2')),
    path('shop3/', include('shop3.urls', namespace='shop3')),
    path('shop4/', include('shop4.urls', namespace='shop4')),
    path('accounts/',include('accounts.urls', namespace='accounts'))
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('about',views.about, name ='about'),
    path('FAQ',views.FAQ, name ='FAQ'),
]

shop1/urls.py
from django.urls import path
from . import views


app_name = 'shop1'

# urlpatterns = [
#     path('', views.product_list, name='product_list'),
#     path('Products', views.product_list, name='product_list'),
#     path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
#     path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
# ]
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<int:id>', views.category_list, name='category_list'),
    path('<int:id>/<int:category_id>/', views.product_detail, name='product_detail'),
    path('search/<int:id>/<int:category_id>/', views.ordering, name='ordering'),
    #path('Create_Ordering<int:id>/<int:category_id>/', views.ordering, name='ordering'),
    #path('<int:id>', views.shop1, name='shop1'),
    #path('search', views.search, name='search'),
]

shop3/urls.py
from django.urls import path
from . import views

app_name = 'shop3'

urlpatterns = [
    path('', views.baking_studio, name='baking_studio'),
    path('Baking_studio', views.baking_studio, name='baking_studio'),
    path('Booking', views.booking, name='booking'),
    path('check_availability/', views.check_availability, name='check_availability'),
    path('Booking_information', views.product_list, name='product_list'),
    path('Products/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

templates/partials/_alert.html
{% if messages %}
<!------if there is andy messages then loop the message object------------------------>
{% for message in messages %}
<div class="container">
<div id = "message" >
    <div class="alert alert-{{message.tags}}" alert dismissable text-center role='alert'>
        
        <strong>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} Error : {% else %}
            {{message.tags | title }}
            {% endif %}
                
        </strong> {{message}}

        <button type='button' class= "close" data-dismiss='alert'>
            <span aria-hidden='true'>&times;</span>
        </button>
    </div>
</div>
</div>
{% endfor %}
{% endif %}

templates/partials/_footer.html
 <!-- Footer -->
  
 <footer id="main-footer" class="py-2 bg-primary text-white text-center">
    Copyright &copy;
    <span class="year"></span> My Cake Shop
  </footer>

templates/partials/_navbar.html
{% load static %}
<style>
    .navbar-brand .logo {
        width: 1rem; /* Logo size: double the character size */
        height: auto; /* Maintain aspect ratio */
    }
    .navbar-nav .nav-link {
        font-size: 0.6rem; /* Half the original font size */
    }
    .cart-info {
        font-size: 0.6rem; /* Match cart info size with nav links */
        /*  white-space: nowrap; */   /* Prevent line breaks */
    }
    .navbar-nav .nav-link .cart-info {
        color: #333; /* Darker color for better contrast */
}
    .custom-bg {
        background-color: #e0e0e0; /* Medium gray */
    }
</style>

<nav class="navbar navbar-expand-lg navbar-light custom-bg  sticky-top">
    <div class="container">

        <!-- Show logo -->
        <a class="navbar-brand" href="{% url 'shop:index' %}">
            <img src="{% static 'img/logo.png' %}" class="logo" alt="Logo" />
        </a>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Expanded navbar -->
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if '/' == request.path %}active{% endif %}">
                    <a class="nav-link" href="{% url 'shop:index' %}">Home</a>
                </li>
                <li class="nav-item {% if 'about' in request.path %}active{% endif %}">
                    <a class="nav-link" href="{% url 'shop:about' %}">About</a>
                </li>
                <li class="nav-item {% if 'shop1' in request.path %}active{% endif %}">
                    <a class="nav-link" href="{% url 'shop1:product_list' %}">Order Cake</a>
                </li>
                <li class="nav-item {% if 'shop2' in request.path %}active{% endif %}">
                    <a class="nav-link" href="{% url 'shop2:product_list' %}">Baking Workshop</a>
                </li>
                <li class="nav-item {% if 'shop3' in request.path %}active{% endif %}">
                    <a class="nav-link" href="{% url 'shop3:baking_studio' %}">Self-Service Baking Studio</a>
                </li>

                <li class="nav-item {% if 'shop4' in request.path %}active{% endif %}">
                    <a class="nav-link" href="{% url 'shop4:product_list' %}">Store</a>
                </li>

                <li class="nav-item {% if 'FAQ' in request.path %}active{% endif %}">
                    <a class="nav-link" href="{% url 'shop:FAQ' %}">FAQ</a>
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item {% if 'dashboard' in request.path %}active{% endif %}">
                      <a class="nav-link" href="{% url 'accounts:dashboard' %}">
                            <i class="fas fa-user-plus"></i> Welcome {{ user.username }} (Dashboard)
                        </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#" onclick="event.preventDefault(); document.getElementById('logout').submit();">
                            <i class="fas fa-sign-out-alt"></i> Logout
                        </a>
                        <form action="{% url 'accounts:logout' %}" method="POST" id="logout" style="display: none;">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.path }}">
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item {% if 'register' in request.path %}active{% endif %}">
                      <a class="nav-link" href="{% url 'accounts:register' %}">
                            <i class="fas fa-user-plus"></i> Register
                        </a>
                    </li>
                    <li class="nav-item {% if 'login' in request.path %}active{% endif %}">
                      <a class="nav-link" href="{% url 'accounts:login' %}">
                            <i class="fas fa-sign-in-alt"></i> Login
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
    <!-- Subheader for cart information -->
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav w-100">
            <div class="nav-item cart-info">
                {% with total_items=cart|length %}
                    {% if total_items > 0 %}
                        Your cart: <a href="{% url 'cart:cart_detail' %}">
                            {{ total_items }} item{{ total_items|pluralize }}, ${{ cart.get_total_price }}
                        </a>
                    {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </div>
        </div>
    </div>
</nav>

templates/partials/_navbar_bak.html
{% load static %}
<style>
    .navbar-brand .logo {
        width: 1rem; /* Logo size: double the character size */
        height: auto; /* Maintain aspect ratio */
    }
    .navbar-nav .nav-link {
        font-size: 0.6rem; /* Half the original font size */
    }
    .cart-info {
        font-size: 0.6rem; /* Match cart info size with nav links */
        /*  white-space: nowrap; */   /* Prevent line breaks */
    }
    .navbar-nav .nav-link .cart-info {
        color: #333; /* Darker color for better contrast */
}
    .custom-bg {
        background-color: #e0e0e0; /* Medium gray */
    }
</style>

<nav class="navbar navbar-expand-lg navbar-light custom-bg  sticky-top">
    <div class="container">

        <!-- Show logo -->
        <a class="navbar-brand" href="{% url 'shop:index' %}">
            <img src="{% static 'img/logo.png' %}" class="logo" alt="Logo" />
        </a>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Expanded navbar -->
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if '/' == request.path %}active{% endif %}">
                    <a class="nav-link" href="{% url 'shop:index' %}">Home</a>
                </li>
                <li class="nav-item {% if 'about' in request.path %}active{% endif %}">
                    <a class="nav-link" href="{% url 'shop:about' %}">About</a>
                </li>
                <li class="nav-item {% if 'shop1' in request.path %}active{% endif %}">
                    <a class="nav-link" href="{% url 'shop1:product_list' %}">Order Cake</a>
                </li>
                <li class="nav-item {% if 'shop2' in request.path %}active{% endif %}">
                    <a class="nav-link" href="{% url 'shop2:product_list' %}">Baking Workshop</a>
                </li>
                <li class="nav-item {% if 'shop3' in request.path %}active{% endif %}">
                    <a class="nav-link" href="{% url 'shop3:baking_studio' %}">Self-Service Baking Studio</a>
                </li>
                <li class="nav-item {% if 'shop4' in request.path %}active{% endif %}">
                    <a class="nav-link" href="{% url 'shop4:product_list' %}">Store</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item {% if 'dashboard' in request.path %}active{% endif %}">
                      <a class="nav-link" href="{% url 'accounts:dashboard' %}">
                            <i class="fas fa-user-plus"></i> Welcome {{ user.username }} (Dashboard)
                        </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#" onclick="event.preventDefault(); document.getElementById('logout').submit();">
                            <i class="fas fa-sign-out-alt"></i> Logout
                        </a>
                        <form action="{% url 'accounts:logout' %}" method="POST" id="logout" style="display: none;">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.path }}">
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item {% if 'register' in request.path %}active{% endif %}">
                      <a class="nav-link" href="{% url 'accounts:register' %}">
                            <i class="fas fa-user-plus"></i> Register
                        </a>
                    </li>
                    <li class="nav-item {% if 'login' in request.path %}active{% endif %}">
                      <a class="nav-link" href="{% url 'accounts:login' %}">
                            <i class="fas fa-sign-in-alt"></i> Login
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
    <!-- Subheader for cart information -->
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav w-100">
            <div class="nav-item cart-info">
                {% with total_items=cart|length %}
                    {% if total_items > 0 %}
                        Your cart: <a href="{% url 'cart:cart_detail' %}">
                            {{ total_items }} item{{ total_items|pluralize }}, ${{ cart.get_total_price }}
                        </a>
                    {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </div>
        </div>
    </div>
</nav>

templates/partials/_topbar.html
<style>
  #top-bar {
      font-size: 0.7rem; /* Set font size to half */
  }
</style>

<!-- Top Bar -->
<section id="top-bar" class="p-1">
  <div class="container">
      <div class="row">
          <div class="col-md-4">
              <i class="fas fa-phone"></i> (852)-555-5555
          </div>
          <div class="col-md-4">
              <i class="fas fa-envelope-open"></i> contact@bcmycakeshop.com
          </div>
          <div class="col-md-4">
              <div class="social text-right">
                  <a href="#">
                      <i class="fab fa-twitter"></i>
                  </a>
                  <a href="#">
                      <i class="fab fa-facebook"></i>
                  </a>
                  <a href="#">
                      <i class="fab fa-linkedin"></i>
                  </a>
                  <a href="#">
                      <i class="fab fa-instagram"></i>
                  </a>
                  <a href="#">
                      <i class="fab fa-pinterest"></i>
                  </a>
              </div>
          </div>
      </div>
  </div>
</section>