cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('shop.urls', namespace='shop')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('shop1/', include('shop1.urls', namespace='shop1')),
    path('shop2/', include('shop2.urls', namespace='shop2')),
    path('shop3/', include('shop3.urls', namespace='shop3')),
    path('shop4/', include('shop4.urls', namespace='shop4')),
    path('accounts/',include('accounts.urls', namespace='accounts'))
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),

]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('about',views.about, name ='about'),
    path('FAQ',views.FAQ, name ='FAQ'),
]

shop1/urls.py
from django.urls import path
from . import views


app_name = 'shop1'

# urlpatterns = [
#     path('', views.product_list, name='product_list'),
#     path('Products', views.product_list, name='product_list'),
#     path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
#     path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
# ]
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<int:id>', views.category_list, name='category_list'),
    path('<int:id>/<int:category_id>/', views.product_detail, name='product_detail'),
    path('search/<int:id>/<int:category_id>/', views.ordering, name='ordering'),
    #path('Create_Ordering<int:id>/<int:category_id>/', views.ordering, name='ordering'),
    #path('<int:id>', views.shop1, name='shop1'),
    #path('search', views.search, name='search'),
]

shop1/forms.py
from django import forms
from .models import Ordering

class Create_Ordering(forms.ModelForm):
    class Meta:
        model = Ordering
        #fields = ['id', 'OrderingDT', 'OrderingConfirm', 'ContactPerson', 'ContactNumber', 'Qty', 'CakeSize', 'CakeWeight', 'CakeDesc', 'PickupDelivery', 'PickupDeliveryTime', 'DeliveryAddr', 'DeliveryCharges', 'product_id', 'ContactEmail', 'category_id', 'CakePrice', 'OrderAmount']
        
        # 'id', 'OrderingConfirm', 'OrderingDT' is omitted
        #fields = ['ContactPerson', 'ContactNumber', 'Qty', 'CakeSize', 'CakeWeight', 'CakeDesc', 'PickupDelivery', 'PickupDeliveryTime', 'DeliveryAddr', 'DeliveryCharges', 'product_id', 'ContactEmail', 'category_id', 'CakePrice', 'OrderAmount']
        
        fields = [
                    'ContactPerson',
                    'ContactNumber',
                    'ContactEmail',
                    'Qty',
                    'CakeSize',
                    'CakeWeight',
                    'CakeDesc',
                    'CakePrice',
                    'PickupDelivery',
                    'PickupDeliveryTime',
                    'PickupDeliveryDate',
                    'DeliveryAddr',
                    'DeliveryCharges',
                    'OrderAmount',
                    'Category_id',
                    'Product_id',
                    'Session_Key'
        ]

shop1/views.py
import calendar
from django.shortcuts import render, get_object_or_404, redirect
from cart.forms import CartAddProductForm
from shop.models import Category, Product
from shop1.models import ProductDetail, Ordering
from django.core.paginator import EmptyPage,PageNotAnInteger, Paginator
from datetime import datetime, timedelta
from .forms import Create_Ordering
from django.utils import timezone
from cart.cart import Cart
from cart.forms import CartAddProductForm
from decimal import Decimal
from django.conf import settings
from django.contrib.sessions.models import Session
import json
from decimal import Decimal
import uuid

def generate_uuid_key():
    return str(uuid.uuid4())

#<Hard Code Table> from listings.choices import price_choices, bedroom_choices, district_choices


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.filter(shop_id=1).order_by('id')
        
    #! Display all available products
    #listings = Listing.objects.order_by('-list_date').filter(is_published=True)[:3]
    #products = Product.objects.filter(available=True)[:Number of records display]
    products = Product.objects.filter(available=True, shop_id=1).order_by('name')
    
    print("[product_list] No. of categories:" , len(categories))
    print("[product_list] No. of products:" , len(products))
    
    paginator = Paginator(products, 3)
    page = request.GET.get('page')
    paged_products = paginator.get_page(page)
    # @ pass database records into listings context
 
    context = {
                'category': category,
                'products': products,
                'categories': categories,
    }
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop1/product/list.html',
                  context)
                  

def category_list(request, id, category_slug=None):
    category = None
    #! Display all categories
    categories = Category.objects.filter(shop_id=1)
    CategoryName = Category.objects.get(id=id)
    
    print("[category_detail] Categories Name:" , CategoryName)

    #! Display all available products
    #listings = Listing.objects.order_by('-list_date').filter(is_published=True)[:3]
    #products = Product.objects.filter(available=True)[:Number of records display]
    products = Product.objects.filter(available=True, category_id=id)
    
    paginator = Paginator(products, 3)
    page = request.GET.get('page')
    paged_products = paginator.get_page(page)
    # @ pass database records into listings context
    #context = {'products': paged_products}
    
    print("[category_detail] Categories Name:" , CategoryName)
    
    context = {
                'category': category,
                'products': products,
                'category_name': CategoryName
    }
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop1/product/category.html',
                   context)


def product_detail(request, id, category_id):
    
    product = get_object_or_404(Product,
                                id=id)
    
    CategoryName = Category.objects.get(id=category_id)
    

    ProductDetail = ProductDetail.objects.filter(product_id_id=id)

    ProductDetail_Item = product.name

    if ProductDetail:
        print("ProductDetail_Item:" , ProductDetail_Item)
        print("Categories Name:" , CategoryName)
    
    cart_product_form = CartAddProductForm()
   
    dDeliveryDateList = {}
    x = range(2, 14)
    for n in x:
        pday01 = datetime.now()
        pdayN = pday01 + timedelta(n)
        dDeliveryDateList[n] = pdayN.strftime('%Y-%m-%d') + " , " + pdayN.strftime('%A')
        
        print("Day", n, pdayN.strftime('%Y-%m-%d'))
        print("Day", pdayN.strftime('%A'))   

    present_day = datetime.now()
    Earliest_date = present_day + timedelta(2)
    print("present_day", present_day.strftime ('%Y-%m-%d'))    
    print("DeliveryDate.items", dDeliveryDateList)

    return render(request,
                  'shop1/product/detail.html',
                  {'product': product,
                   'category': CategoryName,
                   'cart_product_form': cart_product_form,
                   'ProductDetail_Item': ProductDetail_Item,
                   'present_day': present_day,
                   'fastest': Earliest_date,
                   'DeliveryDate': dDeliveryDateList})
    

def ordering(request, id, category_id):
    print("ordering: [request.POST]" , request.POST) 
    

    if request.method == 'POST':
        form = Ordering(request.POST)
        
        ContactPerson = request.POST.get('ContactPerson').strip()
        ContactNumber = request.POST.get('ContactNumber').strip()
        ContactEmail = request.POST.get('ContactEmail').strip()
        Qty = int(request.POST.get('Qty'))

        if 'CakeSizeWeightPrice' in request.POST:
            input_string = request.POST.get('CakeSizeWeightPrice')
            parts = input_string.split("/")
            CakeSize = parts[0]
            CakeSize = CakeSize.strip()
            CakeWeight = parts[1]
            CakeWeight = CakeWeight.strip()
            CakeDesc = parts[2]
            CakeDesc = CakeDesc.strip()
            CakePrice = int(parts[3])

        if 'PickupDelivery' in request.POST:
            input_string = request.POST.get('PickupDelivery')
            parts = input_string.split("/")
            PickupDelivery = parts[0]
            PickupDelivery = PickupDelivery.strip()
            DeliveryCharges = int(parts[1])

        if 'PickupDeliveryDate' in request.POST:
            dDeliveryDateList = {}
            PickupDeliveryDate = request.POST.get('PickupDeliveryDate')
            print("request.POST.get('PickupDeliveryDate')", request.POST.get('PickupDeliveryDate'))

            x = range(2, 14)
            for n in x:
                pday01 = datetime.now()
                pdayN = pday01 + timedelta(n)
                dDeliveryDateList[n] = pdayN.strftime('%Y-%m-%d')
                print(n , dDeliveryDateList[n])
                print("dDeliveryDateList[PickupDeliveryDate]", n, pdayN.strftime('%Y-%m-%d'))  

            PickupDeliveryDate = dDeliveryDateList[int(request.POST.get('PickupDeliveryDate'))]
            print("dDeliveryDateList[PickupDeliveryDate]", dDeliveryDateList[int(request.POST.get('PickupDeliveryDate'))])
            present_day = datetime.now()
            fastest = present_day + timedelta(2)
            
            print("present_day", present_day)  
            print("DeliveryDate.items", dDeliveryDateList)

        
        PickupDeliveryTime = request.POST.get('PickupDeliveryTime').strip()
        DeliveryAddr = request.POST.get('DeliveryAddress').strip()  
        Amount = (int(Qty) * int(CakePrice)) + int(DeliveryCharges)   
        Product_id = int(id)
        Category_id = int(category_id)

        OrderingDT = datetime.now()


        # for generation of key linking the product detail
        uuid_key = generate_uuid_key()
        print(uuid_key)        

        
        context = {
            'OrderingDT': OrderingDT,
            'OrderingConfirm': False,
            'ContactPerson': ContactPerson,
            'ContactNumber': ContactNumber,
            'ContactEmail': ContactEmail,
            'Qty': Qty,
            'CakeSize': CakeSize,
            'CakeWeight': CakeWeight,
            'CakeDesc': CakeDesc,
            'CakePrice': CakePrice,
            'PickupDelivery': PickupDelivery,
            'PickupDeliveryTime': PickupDeliveryTime,
            'PickupDeliveryDate': PickupDeliveryDate,
            'DeliveryAddr': DeliveryAddr,
            'DeliveryCharges': DeliveryCharges,
            'OrderAmount': Amount,
            'Product_id': Product_id,
            'Category_id': Category_id
            }

        # to to confirmation page


        print(" ---context---:", context)
        print("form.is_valid()", form.is_valid())
    if form.is_valid():
        
        #---------------- Tbl: Ordering ---------------- 
        print("//form.is_valid //" ,context) 
        #form.save()  # Save the form data to the database 
        
        new_order = Ordering.objects.create(
                    ContactPerson = ContactPerson,
                    ContactNumber = ContactNumber,
                    ContactEmail = ContactEmail,
                    Qty = Qty,
                    CakeSize = CakeSize,
                    CakeWeight = CakeWeight,
                    CakeDesc = CakeDesc,
                    CakePrice = CakePrice,
                    PickupDelivery = PickupDelivery,
                    PickupDeliveryTime = PickupDeliveryTime,
                    PickupDeliveryDate = PickupDeliveryDate,
                    DeliveryAddr = DeliveryAddr,
                    DeliveryCharges = DeliveryCharges,
                    OrderAmount = Amount,
                    Product_id = Product_id,
                    Category_id = Category_id,
                    Session_Key = request.session.session_key)
        new_order_id = new_order.id  # Get the ID of the newly created record
            
        print("---New Ordering ID--- ",new_order_id)
        print("session_id:", request.session.session_key)
            
        Msg = "Add to the cart!"
        
        print("----Cart----", new_order)
        
        #return redirect('success')  # Redirect after saving
        
        cart = []
        session_key = []
        
        if 'Msg' in locals():
            # Loading Cart
            print("'Msg' in locals()", 'Msg' in locals())
            if Msg is not None:
                queryset_list = Ordering.objects.order_by('-OrderingDT')
                
                sessions = Session.objects.all()

                for session in sessions:

templates/shop1/product/category.html
{% extends "shop1/base.html" %}
{% comment %} {% extends 'base.html' %} {% endcomment %}
{% load humanize %}
{% load static %}

{% block title %}
  {% if products %}Browse Cakes By Catalog: {{category_name}}{% endif %}
{% endblock %}

{% block content %}
  <section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12" style="background-color: #e5c9a3;">
          {% if products %}
          <h1 class="display-4"> Browse Cakes: <b>{{category_name}}</b> Catalog </h1>
          {% endif %}
          <p class="lead">
            Sharing the cake with loved ones, it represents the joy, happiness, celebrations and thanksgiving.
          </p>
        </div>
      </div>
    </div>
  </section>
  
  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <i class="fas fa-home"></i> 
            <a href="/shop1/">Order Cakes</a>
          </li>
          {% if products %}
          <li class="breadcrumb-item">Browse Cakes By Catalog: {{category_name}} </li>
          {% endif %}
        </ol>
      </nav>
    </div>
  </section>
  
  <!-- Listings -->
  <section id="listings" class="py-4">
    <div class="container">
      <div class="row">
        <!-- Listing 1 -->
        {% comment %}
        {% if listings %}
        {% for listing in listings %}
        {% endcomment %}
        {% if products %}
        {% for product in products %} 
        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card listing-preview">
            <img class="card-img-top" src={{product.image.url}} alt="" />
            <div class="card-img-overlay">
              <h2>
                <!--<span class="badge badge-secondary text-white">${{product.price | intcomma }}</span>-->
                <span class="badge badge-secondary text-white" style="background-color: #e9bf85;">${{product.price | intcomma }}</span>
              </h2>
            </div>
            <div class="card-body">
              <div class="listing-heading text-center">
                <h4 class="text-primary">{{product.name}}</h4>
                <p style="text-align: left;">
                  <!--<i class="fas fa-map-marker text-secondary"></i>{{product.description}}-->
                  <i class="fas fa-folder-open " style="color: #e9bf85"></i>  
                  <span style="font-size: 15px;">{{category_name}}</span> 
                  <br />
                  <i class="fas fa-tags" style="color: #e9bf85"></i>
                  <span style="font-size: 15px;">{{product.description}}</span>  
                </p>
              </div>
              {% comment %}  
              <hr />
              <div class="row py-2 text-secondary">
                <div class="col-6">
                  <i class="fas fa-th-large"></i> Sqft: {{listing.sqft | intcomma}}
                </div>
                <div class="col-6">
                  <i class="fas fa-dumbbell"></i> ClubHouse: {{listing.clubhouse}}
                </div>
              </div>
              <div class="row py-2 text-secondary">
                <div class="col-6"><i class="fas fa-bed"></i> Bedrooms: {{listing.bedrooms}}</div>
                <div class="col-6"><i class="fas fa-bath"></i> Bathrooms: {{listing.bathrooms}}</div>
              </div>
              {% endcomment %}
              {% comment %}
              <hr />
              <div class="row py-2 text-secondary">
                <div class="col-12"><i class="fas fa-user"></i> {{listing.realtor}}</div>
              </div>
              <div class="row text-secondary pb-2">
                <div class="col-6"><i class="fas fa-clock"></i> {{listing.list_date | timesince}}</div>
              </div>
              {% endcomment %}
              <hr />
              <a href="{% url 'shop1:product_detail' product.id product.category_id %}" class="btn btn-primary btn-block">Cake Ordering</a>
            </div>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="col-md-12">
        <p>No Available Product</p>
      </div>
        {% endif %}
      
      </div>
  
      <div class="row">
        <div class="col-md-12">
          <!-- pagination part of the code-->
          {% if list.has_other_pages %}
          <ul class="pagination">
            {% if list.has_previous %}
            <li class="page-item">
              <a href="?page={{list.previous_page_number}}" class="page-link">&laquo;</a>
            </li>  
            {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#">&laquo;</a>
            </li>
            {% endif %}
            <!-- use for loop to gen page numbers -->
            {% for i in list.paginator.page_range %}
            <!-- check current page, then change the button color -->
            {% if list.number == i %}
            <li class="page-item active">
              <a class="page-link">{{i}}</a>
            </li>
            {% else %}
           <li class="page-item">
              <a class="page-link" href="?page={{i}}">{{i}}</a>
            </li> 
            {% endif %}
            {% endfor %}
            
            <!-- next button -->
            {% if list.has_next %}
            <li class="page-item">
            <a href="?page={{list.next_page_number}}" class="page-link" >&raquo;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#">&raquo;</a>
            </li>
            {% endif %}
          </ul>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/shop1/product/list.html
{% extends "shop1/base.html" %}
{% comment %} {% extends 'base.html' %} {% endcomment %}
{% load humanize %}
{% load static %}

{% block title %}
  {% if products %}list Browse Cakes{% endif %}
{% endblock %}

{% block content %}
  <section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12" style="background-color: #e5c9a3;">
          <h1 class="display-4">Browse Our Cakes</h1>
          <p class="lead">
            Sharing the cake with loved ones, it represents the joy, happiness, celebrations and thanksgiving.
          </p>
        </div>
      </div>
    </div>
  </section>
  
  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/shop1/" <i class="fas fa-home"></i> Order Cakes</a>
          </li>
          <li class="breadcrumb-item active">Browse Cakes</li>
        </ol>
      </nav>
    </div>
  </section>
  
  <!-- Listings -->
  <section id="listings" class="py-4">
    <div class="container">
      <div class="row">
        <!-- Listing 1 -->
        {% comment %}
        {% if listings %}
        {% for listing in listings %}
        {% endcomment %}
        {% if products %}
        {% for product in products %} 
        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card listing-preview">
            <img class="card-img-top" src="{{product.image.url}}" alt="" />
            <div class="card-img-overlay">
              <h2>
                <!--<span class="badge badge-secondary text-white">${{product.price | intcomma }}</span>-->
                <span class="badge badge-secondary text-white" style="background-color: #e9bf85;">${{product.price | intcomma }}</span>
              </h2>
            </div>
            <div class="card-body">
              <div class="listing-heading text-center">
                <h4 class="text-primary">{{product.name}}</h4>
                <p style="text-align: left;">
                  <!--<i class="fas fa-map-marker text-secondary"></i>{{product.description}}-->
                  {% if categories %}
                    {% for category in categories %}
                      {% if category.id == product.category_id %}
                        <i class="fas fa-folder-open " style="color: #e9bf85"></i>  
                        <a href="{% url 'shop1:category_list' category.id %}">
                          <span style="font-size: 15px;">{{category.name}}</span>
                        </a> 
                      {% endif %}
                    {% endfor %}
                  {% endif %}
                  <br />
                  <i class="fas fa-tags" style="color: #e9bf85"></i>
                  <span style="font-size: 15px;">{{product.description}}</span>  
                </p>
              </div>
              
              <hr />
              <a href="{% url 'shop1:product_detail' product.id product.category_id %}" class="btn btn-primary btn-block">Cake Ordering</a>
            </div>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="col-md-12">
        <p>No Available Product</p>
      </div>
        {% endif %}
      
      </div>

      
      <div class="row">
        <div class="col-md-12">
          <!-- pagination part of the code-->
          {% if list.has_other_pages %}
          <ul class="pagination">
            {% if list.has_previous %}
            <li class="page-item">
              <a href="?page={{list.previous_page_number}}" class="page-link">&laquo;</a>
            </li>  
            {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#">&laquo;</a>
            </li>
            {% endif %}
            <!-- use for loop to gen page numbers -->
            {% for i in list.paginator.page_range %}
            <!-- check current page, then change the button color -->
            {% if list.number == i %}
            <li class="page-item active">
              <a class="page-link">{{i}}</a>
            </li>
            {% else %}
           <li class="page-item">
              <a class="page-link" href="?page={{i}}">{{i}}</a>
            </li> 
            {% endif %}
            {% endfor %}
            
            <!-- next button -->
            {% if list.has_next %}
            <li class="page-item">
            <a href="?page={{list.next_page_number}}" class="page-link" >&raquo;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#">&raquo;</a>
            </li>
            {% endif %}
          </ul>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/shop1/product/ordering_bak.html
{% extends "shop1/base.html" %}
{% load humanize %}
{% load static %}

{% block title %}
Your shopping cart
{% endblock %}

{% block content %}
<!-- Start: Page Header -->
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12" style="background-color: #e5c9a3;">
                <h1 class="display-4">Your shopping cart</h1>
                <p class="lead">
                    {% if Msg %}{{ Msg }}{% endif %}
                </p>
            </div>
        </div>
    </div>
</section>
<!-- End: Page Header -->

<!-- Start: Breadcrumb -->
<section id="bc" class="mt-3">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/shop1/"><i class="fas fa-home"></i> Order Cakes</a>
                </li>
                <li class="breadcrumb-item active">Shopping Cart</li>
            </ol>
        </nav>
    </div>
</section>
<!-- End: Breadcrumb -->

<!-- Start: Loading Table -->
<!-- {% if Orderings %} -->
<table class="cart">
    <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        {% for item_id, item in session_data.cart.items %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.override }}
                        <input type="submit" value="Update">
                        {% csrf_token %}
                    </form>
                </td>
                <td>
                    <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                        <input type="submit" value="Remove">
                        {% csrf_token %}
                    </form>
                </td>
                <td class="num">${{ item.price }}</td>
                <td class="num">${{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            {% comment %} <td class="num">${{ cart.get_total_price }}</td> {% endcomment %}
            <td class="num">$cart.get_total_price </td>
        </tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url 'shop:index' %}" class="buttonlight">Continue shopping</a>
    <a href="{% url 'orders:order_create' %}" class="button">Checkout</a>
</p>
<!--{% endif %} -->
<!-- End: Loading Table -->
{% endblock %}